### ISSUE TITLE
Backtrace for gem load error

### ISSUE THREAD

**Issue by say2say** [timlentse/ss-panel-rails#1]
执行rails s的时候出现以下错误：

/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'coffee-rails'. (Bundler::GemRequireError)
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in`autodetect'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/execjs-2.7.0/lib/execjs.rb:4:in`<top (required)>'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in`<top (required)>'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in`<top (required)>'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-rails-4.1.1/lib/coffee-rails.rb:1:in `require'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/coffee-rails-4.1.1/lib/coffee-rails.rb:1:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in`block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in`block in require'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in`require'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/root/ss-panel-rails/config/application.rb:7:in`<top (required)>'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `require'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in`block in server'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in`server'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in`<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in`<main>'
Bundler Error Backtrace:
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in`each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in`each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in`require'
        from /root/ss-panel-rails/config/application.rb:7:in `<top (required)>'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in`require'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in`tap'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
        from /root/ss-panel-rails/vendor/bundle/ruby/2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in`require'
        from bin/rails:4:in `<main>'

**Comment by say2say** [comment]
忘记安装nodejs了。。。sorry

**Comment by timlentse** [comment]
请问你也是使用ruby的吗？

say2say notifications@github.com于2016年7月14日周四 上午9:01写道：

**Comment by say2say** [comment]
刚接触ruby没多久

**Comment by timlentse** [comment]
github交个朋友憋？有关ruby不会的问题可以咨询一下我。

say2say notifications@github.com于2016年7月15日周五 下午4:23写道：
