### ISSUE TITLE
注册的建议

### ISSUE THREAD

**Issue by say2say** [timlentse/ss-panel-rails#2]
发现开放注册不需要邀请码了，感觉邀请码这个功能还不错呢

**Comment by timlentse** [comment]
@say2say 邀请码功能很快就会加上，请留意后续的更新。
BTW 欢迎把这个repo分享给有需要的人，你们的建议是我最大的动力。

**Comment by say2say** [comment]
嗯~体验还不错

**Comment by timlentse** [comment]
@say2say 邀请码功能已经添加了

**Comment by say2say** [comment]
`ActionView::Template::Error (Unable to generate hash without :hash_secret):
    48:     </li>
    49:     <li class="dropdown">
    50:       <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    51:          <img class="avatar" src="<%= @current_user.avatar.url(:thumb) %>"/>
    52:         <i class="fa fa-caret-down"></i>
    53:       </a>
    54:       <ul class="dropdown-menu dropdown-user">
  app/views/layouts/_nav.html.erb:51:in`_app_views_layouts__nav_html_erb__3928900041258526923_41101060'
  app/views/users/home.html.erb:2:in `_app_views_users_home_html_erb__1564834378055244942_40204160'`

登录报错，把这句
`<img class="avatar" src="<%= @current_user.avatar.url(:thumb) %>"/>`
注释后可以

**Comment by timlentse** [comment]
@say2say  看readme
