### ISSUE TITLE
第一步就安装不了..

### ISSUE THREAD

**Issue by genics** [timlentse/ss-panel-rails#3]
root@v382:~# git clone git@github.com:timlentse/ss-panel-rails.git
Cloning into 'ss-panel-rails'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
没有权限?

**Comment by timlentse** [comment]
你有没有给你自己的github账户添加公钥啊？

**Comment by genics** [comment]
没有.......没弄过

**Comment by timlentse** [comment]
@genics 这是一个很简单的问题，要不你加一下我QQ，476010464

**Comment by say2say** [comment]
git clone https://github.com/timlentse/ss-panel-rails.git
