### ISSUE TITLE
.

### ISSUE THREAD

**Issue by qwIvan** [timlentse/ss-panel-rails#5]

**Comment by qwIvan** [comment]
也没有默认用户名密码

**Comment by timlentse** [comment]
@qwIvan 你好，你可以通过提供的脚本生成管理员账号，在repo目录下面执行 email=example.com name=helloworld passwd=foo bundle exec rake create_admin

或者你可以关闭验证码功能，然后自己注册一个新的用户（新注册的用户只是普通用户，不具备管理员功能）

关闭验证码功能：把`settings.local.yml`文件中加入 invited_code: false这一行。

**Comment by qwIvan** [comment]
好吧我已经写sql创建了用户。。
