### ISSUE TITLE
安装ruby才是难点吧。。

### ISSUE THREAD

**Issue by yizhitangtongxue** [timlentse/ss-panel-rails#9]
对于没接触过ruby的小伙伴们来说。。。

**Comment by timlentse** [comment]
@yizhitangtongxue ,一键安装脚本`setup.sh`里面就包含安装ruby的功能啊，执行./setup.sh 就会安装ruby跟相关的依赖。

**Comment by yizhitangtongxue** [comment]
root@iZj6chhwq5a6tmxp14y8inZ:/data/wwwroot/test/ss-panel-rails# ./setup.sh
Cloning into 'ss-panel-rails'...
remote: Counting objects: 982, done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 982 (delta 22), reused 0 (delta 0), pack-reused 868
Receiving objects: 100% (982/982), 3.59 MiB | 107.00 KiB/s, done.
Resolving deltas: 100% (509/509), done.
Checking connectivity... done.
./setup.sh: 66: ./setup.sh: bundle: not found
./setup.sh: 67: ./setup.sh: bundle: not found
@timlentse

**Comment by timlentse** [comment]
@yizhitangtongxue 
`第一点` setup.sh里面就包含git clone 命令，所以不需要事先clone再运行 setup.sh脚本
直接这样执行就可以了 `curl -Ssl https://raw.githubusercontent.com/timlentse/ss-panel-rails/master/setup.sh | sh`
`第二点` 你贴出来的错误信息看起来是bundle这个命令不存在，安装ruby这一步的有报错信息吗？ `which ruby`显示的结果是什么？
